apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/reikamoon/argo-demo'
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
